# Generated by Django 3.2.13 on 2022-06-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_main', '0003_auto_20220618_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='finished',
            field=models.DateTimeField(),
        ),
    ]
