# Generated by Django 3.2.13 on 2022-06-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_main', '0004_auto_20220619_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='finished',
            field=models.DateTimeField(null=True),
        ),
    ]
